import Head from 'next/head'
import { Inter } from '@next/font/google'
import Heading from './components/Heading'
import FormComponent from './components/FormComponent'
import CreateButton from './components/CreateButton'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='h-screen overflow-y-hidden bg-[#c5e4e7]'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
        <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;600;700;800&family=Montserrat+Alternates:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"/>
      </Head>
      <div className='flex flex-col h-full m-auto max-w-[64rem] pt-[30px] gap-[20px] relative'>
        <Heading />
        <FormComponent />
        <CreateButton />
      </div>
    </div>
  )
}
